<footer id="section-footer" class="section section-footer">
  <div id="zone-footer-wrapper" class="zone-wrapper zone-footer-wrapper clearfix">
    <div id="zone-footer" class="zone zone-footer clearfix container-16">
      <div class="grid-16 region region-footer-second" id="region-footer-second">
        <div class="region-inner region-footer-second-inner">
          <div class="block block-block block-1 block-block-1 odd block-without-title" id="block-block-1">
            <div class="block-inner clearfix">
              <div class="content clearfix">
                
					<!-- BEGIN FOOTER COPY and PASTE-->
				
           <style>
img, object, embed, video {
	max-width: 100%;
}
/* IE 6 does not support max-width so default to width 100% */
.ie6 img {
	width:100%;
}



/* Mobile Layout: 480px and below. */


.a-twitter, .b-facebook, .c-instagram, .d-youtube, .e-flickr, 
.f-pinterest, .g-linkedin
             { margin-right:5px; }

#zone-footer-wrapper{
	padding:10px 0 20px 0;
	background:#323e48;
	color:#fff;
	overflow:hidden;
	font-family: helvetica, san-serif; 
	font-size:12px;
	
}



.part-1 {
	width:43%;
	
	float:left;
	padding: 0 10px;
}

.part-2 {
	width:42%;
		float:left;
		padding: 0 10px;
border-left:1px dotted #cccccc;

}

.part-2 img, .part-1 img {
	float:left;
	padding:0 10px 0px 0;

}

.part-2 p {
	margin:0;
}

 .part-1 p {
	width:93%;
	float: left;
	margin: 0 20px 0px 0;
	padding: 0;
	font-family: gotham, helvetica;
	font-size: 14px;
	font-weight: bold;
	border-right: none;
	line-height: 1.2em;
}


.column-1 {
	float: left;
	margin-right: 10px;
	border-bottom: 1px dotted #cccccc;
	padding: 10px;
	clear:both;
	width:100%;
}

.column-2 {
	float: left;
	margin-right: 10px;
	border-bottom: 1px dotted #cccccc;
	padding: 10px;
	clear:both;
	width:100%;
}
.column-3 {
	float: left;
	margin-right: 10px;
	border-bottom: 1px dotted #cccccc;
	padding: 10px;
	clear:both;
	width:100%;
}
.column-4 {
	float: left;
	margin-right: 10px;
	padding: 10px;
	clear:both;
	width:100%;
}





.gridContainer {
	margin-left: auto;
	margin-right: auto;
	width: 87.36%;
	padding-left: 1.82%;
	padding-right: 1.82%;
	overflow: hidden;
}

#zone-footer-wrapper h2{ 
	font-family: gotham, helvetica;
font-size: 14px;
font-weight: bold;
border-bottom:none;
margin-bottom:.75em;

}

#zone-footer-wrapper ul{ 
		list-style:none;
		margin-left:0px;
		padding: 0;
		line-height: 132%;
}

#zone-footer-wrapper li{ 
		margin-left:0px;
		margin-bottom: .25em;		
}

#zone-footer-wrapper a{ 
	
		color:white;
		
		
}

.partners {
	border-top: 1px dotted #687C89;
	border-bottom: 1px dotted #687C89;
	padding:15px 0;
	width:100%;
	clear:left;
	margin-top: 20px;
	margin-bottom:20px;
}



#zone-footer .social-icons{
	margin:25px 0 10px 0;
	padding:0;
}
.a-twitter, .b-facebook, .c-instagram, .d-youtube, .e-flickr, 
.f-pinterest, .g-linkedin
{ display: inline-block; background: url('http://www.mnhs.org/static/masthead/mnhs_org/css/megamenu/HTML/img/icons/social_sprite.png') no-repeat; overflow: hidden; text-indent: -9999px; text-align: left; }

#zone-footer .closing{
	padding-top:20px;
}
#zone-footer h2{
	padding-top:0;
}

.column-4 img {
	float:left;
	padding:0 10px 0px 0;
}

.social-icons {
	margin-top:25px;
}
.a-twitter { background-position: -10px -0px; width: 27px; height: 27px; }
.b-facebook { background-position: -47px -0px; width: 27px; height: 27px; }
.c-instagram { background-position: -10px -37px; width: 28px; height: 28px; }
.d-youtube { background-position: -47px -37px; width: 28px; height: 28px; }
.e-flickr { background-position: -10px -74px; width: 27px; height: 27px; }
.f-pinterest { background-position: -47px -74px; width: 27px; height: 27px; }
.g-linkedin { background-position: -10px -111px; width: 27px; height: 27px; }

#zone-footer .part-1 h2 {
width: 88%;
}

/* Tablet Layout: 581px to 768px. Inherits styles from: Mobile Layout. */

@media only screen and (min-width: 600px) {
.gridContainer {
	width: 90.675%;
	padding-left: 1.1625%;
	padding-right: 1.1625%;
}
#LayoutDiv1 {
	clear: both;
	float: left;
	margin-left: 0;
	width: 100%;
	display: block;
}

.footer_column {
	clear:none;
	border-bottom: none;
	border-right: 1px dotted #cccccc;
	width: 200px;
	
}

.column-1 {
	float: left;
	margin-right: 10px;
	border-right: 1px dotted #cccccc;
	border-bottom: none;
	padding: 10px;
	width:44%;
	clear:none;
	height:155px;
}

.column-1 p {
	margin-left:0px;
}

.column-2 {
	float: left;
	margin-right: 10px;
	border-bottom: 1px dotted #cccccc;
	padding: 10px;
	width:44%;
	clear:none;
	height:155px;
}
.column-3 {
	float: left;
	margin-right: 10px;
	border-top: 1px dotted #cccccc;
	border-right: 1px dotted #cccccc;
	border-bottom: none;
	padding: 10px;
	width:44%;
	clear:none;
	height:155px;
}
.column-4 {
	float: left;
	margin-right: 10px;
	padding: 10px;
	width:44%;
	clear:none;
	height:155px;
	border-bottom: none;
}

.part-1 {
	width:44%;
	float:left;
	padding: 0 10px;
}

.part-2 {
	width:47%;
		float:left;
		padding: 0 10px;

}



.part-1 img {
float: left;
padding: 0 4px 0px 0;
}

#zone-footer .part-1 h2 {
width: 88%;
}
}


/* Desktop Layout: 769px to a max of 1232px.  Inherits styles from: Mobile Layout and Tablet Layout. */

@media only screen and (min-width: 769px) {
.gridContainer {
	width: 99.5%;
	max-width: 1232px;
	padding-left: 0.75%;
	padding-right: 0.75%;
	margin: auto;
}
#LayoutDiv1 {
	clear: both;
	float: left;
	margin-left: 0;
	width: 100%;
	display: block;
}

.a-twitter, .b-facebook, .c-instagram, .d-youtube, .e-flickr, 
.f-pinterest, .g-linkedin
             { margin-right:0px; }


/*columns */

/*.column-1 {
	float: left;
	margin-right: 10px;
	border-bottom: 1px dotted #cccccc;
	padding: 10px;
	clear:both;
	width:100%;
}*/


.column-1:before, .column-1 {
	width:21%;}

.column-1 {
	float: left;
	border-right: 1px dotted #cccccc;
	border-bottom: none;
	padding: 11px;
height: 169px;
}





/* column 2 */


.column-2:before, .column-2 {
	width:19%;
	}

.column-2 {
	float: left;
	border-right: 1px dotted #cccccc;
	border-bottom: none;
	padding: 11px;
height: 169px;
}





/* column 3 */

.column-3:before, .column-3 {
	width:19%;
	}

.column-3 {
	float: left;
	border-right: 1px dotted #cccccc;
		border-top: none;
height: 169px;
	padding: 11px;
	border-bottom: none;
}




/* column 4 */
.column-4:before, .column-4 {
	width:21%;
	}

.column-4 {
	float: left;
	padding: 11px;
	border-bottom: none;
height: 169px;
}




.part-1 {
	width:44%;
	float:left;
	padding: 0 10px;
}

.part-2 {
	width:46%;
		float:left;
		padding: 0 10px;

}

 .part-1 h2 {
	width:30px;
	float:left;
	margin: 0 60px 0 0;
}

 .part-1 p {
	width:60px;

}

.part-1 img {
margin: 0 0 0 15px;
}

.partners {
	border-top: 1px dotted #cccccc;
	border-bottom: 1px dotted #cccccc;
}


}

@media only screen and (min-width: 970px) {


	.column-1,.column-2,.column-3,.column-4 {
	height: 130px;
}

}

@media only screen and (min-width: 1180px) {

.part-1 {
width: 43%;
}	
	.column-1,.column-2,.column-3,.column-4 {
	height: 130px;
}

}

</style>









<div id="zone-footer-wrapper">
<div class="gridContainer">
  <div class="column-1"><h2 class="no-border">Minnesota Historical Society</h2>

		<p>345 W. Kellogg Blvd. <br />
		  St. Paul, MN 55102<br />
		  651-259-3000 &#8226; 1-800-657-3773<br />
	</p>
        <p><a href="http://www.mnhs.org/contact">Contact MNHS</a> &#8226; <a href="http://www.mnhs.org/visit">Locations &amp; Hours </a></p> </div>



  <div class="column-2"><h2 class="no-border">Resources</h2>
	<ul>
		<li><a href="http://www.mnhs.org/media">Media Room</a></li>
        <li><a href="http://shop.mnhs.org">Shop</a></li>
        <li><a href="http://blogs.mnhs.org">Blogs</a></li>
      
	</ul></div>



  <div class="column-3"><h2 class="no-border">Opportunities</h2>
	<ul class="grid-2">
		<li><a href="http://www.mnhs.org/volunteers">Volunteers</a></li>
		<li><a href="http://www.mnhs.org/internships">Internships</a></li>
		<li><a href="http://www.mnhs.org/jobs">Jobs</a></li>
         <li><a href="http://www.mnhs.org/fellowships">Fellowships</a></li>
	</ul></div>


  <div class="column-4"><h2 class="no-border">Connect with MNHS</h2>
    <a href="http://www.mnhs.org/newsletters/"><img src="http://www.mnhs.org/static/masthead/mnhs_org/img/social/newsletter.png" alt="Sign up for email newsletters" /></a> <a href="http://www.mnhs.org/newsletters/">MNHS Email Newsletters </a>
<div class="social-icons">
	   <a href="http://twitter.com/mnhs"><div class=" a-twitter">MNHS twitter</div></a>

		<a href="https://www.facebook.com/minnesotahistoricalsociety"><div class=" b-facebook">MNHS facebook</div></a>

	<a href="http://instagram.com/minnesotahistoricalsociety/"><div class=" c-instagram">MNHS instagram</div></a>

		<a href="https://www.youtube.com/user/minnesotahistory"><div class=" d-youtube">MNHS youtube</div></a>

		<a href="https://www.flickr.com/photos/minnesotahistoricalsociety/"><div class=" e-flickr">MNHS flickr</div></a>

		<a href="http://www.pinterest.com/mnhistory/"><div class=" f-pinterest">MNHS pinterest</div></a>

		<a href="http://www.linkedin.com/company/minnesota-historical-society"><div class="g-linkedin">MNHS linkedin</div></a>
	</div></div>
    </div>
    
<div class="partners"> <div class="gridContainer">
      <div class="part-1"><p class="part-1">Premier partners</p>
      <a href="http://www.xcelenergy.com/Save_Money_&amp;_Energy"><img src="http://www.mnhs.org/static/masthead/mnhs_org/img/social/xcel-copy.png" alt="Xcel Energy" /></a><a href="http://www.exploreminnesota.com/"><img src="http://www.mnhs.org/static/masthead/mnhs_org/img/social/explore_mn.png" alt="Explore Minnesota" /></a> </div>
<div class="part-2"><a href="http://legacy.mnhs.org/"><img src="http://www.mnhs.org/static/masthead/mnhs_org/img/social/clean_water_legacy.png" alt="Clean Water Land & Legacy Amendment" /></a><p>Funding provided by the State of Minnesota, the <a href="http://legacy.mnhs.org/">Legacy Amendment </a>through the vote of Minnesotans on Nov. 4, 2008, and our generous donors and members.</p></div>

    </div>
    </div>
    <div class="gridContainer"style="
    text-align: center;"><a href="http://www.mnhs.org/copyright">Copyright</a> &#8226; <a href="http://www.mnhs.org/privacy">Privacy</a> &#8226; <a href="http://www.mnhs.org/informationpolicy">Information Policy </a></div>


<!-- END FOOTER COPY and PASTE -->

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
	<div class="clear"></div>
  </div>
</footer>
<script>
// installed by cjp 6-23-2014
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-9226775-1', 'auto');
  ga('send', 'pageview');
</script>
