<!-- ****Start Masthead**** -->
<div id="masthead">
  <div class="container-12">
    <div class="grid-12">
      <div id="mhs-logo"> <a href="http://www.mnhs.org/"><img alt="Minnesota Historical Society" src="/static/masthead/mnhs_org/img/mnhs-logo-white.svg"  onError="this.onerror=null;this.src='/static/masthead/mnhs_org/img/mnhs-logo-white.png';"></a> </div>
      <div id="search-secondaryLinks">
        <div id="secondaryLinks">
          <ul>
            <li><a href="http://sites.mnhs.org/support/membership">Membership</a> | </li>
            <li><a href="http://shop.mnhs.org/">Shop</a> | </li>
            <li> <a href="http://www.mnhs.org/calendar">Calendar</a> | </li>
            <li><a href="http://sites.mnhs.org/support/make-gift">Donate</a></li>
          </ul>
        </div>
        <div id="global-search">
          <form method="get" class="global-search-form" action="http://search.mnhs.org/">
            <input onkeypress="return checkSubmit(event);" class="input-box" type="text" name="q" maxlength="75" size="75">
            <input type="hidden" value="websites" name="tab">
            <input type="image" src="/static/masthead/mnhs_org/img/search.png" name="Search" alt="Search" class="searchKeyword">
          </form>
        </div>
        <!-- end div id=global-search --> 
      </div>
    </div>
  </div>
  <div class="clear"> </div>
</div>
<!-- end masthead-->
<!-- ****Start Navbar**** -->
<div class="navbar affix-top" data-spy="affix" data-offset-top="85">
<div class="container-12">
  <div id="zone-wrapper"> 
    <div class="navbar-header">
      <button type="button" data-toggle="collapse" data-target="#navbar-collapse-1" class="navbar-toggle"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
    </div>
    <nav id="navbar-collapse-1" class="navbar-collapse collapse" role="navigation">
      <ul class="nav navbar-nav">
        <!-- Begin Logo Link -->
        <li class="navbar-brand"><a href="http://www.mnhs.org/"><img  alt="Minnesota Historical Society" src="/static/masthead/mnhs_org/img/mnhs-logo-mflame-white-small.svg" onError="this.onerror=null;this.src='/static/masthead/mnhs_org/img/mnhs-logo-mflame-white-small.png';" /></a> </li>
        <!-- End Logo Link --> 
        <!-- Begin Visit Tab -->
        <li class="dropdown visit"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Visit<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> 
              <!-- Begin Visit Menu Content -->
              <div class="dropmenu-content">
                <div class="container">
                  <div class="row overview-section">
                    <div class="grid-8"> <a href="http://www.mnhs.org/visit">Overview</a>
					</div>
                  </div>
                  <div class="row">
                    <div class="grid-2">
                      <h3 class="menu-feature"> <a href="http://www.mnhs.org/calendar">Calendar</a> </h3>
                      <ul class="menu">
                        <li><a href="http://www.mnhs.org/calendar?c=American Indian">American Indian Events</a></li>
                        <li><a href="http://www.mnhs.org/calendar?c=Camps">Camps</a></li>
                        <li><a href="http://www.mnhs.org/calendar?c=Classes and Workshops">Classes and Workshops</a></li>
                        <li><a href="http://www.mnhs.org/calendar?c=Family">Family Events</a></li>
                        <li><a href="http://www.mnhs.org/calendar?c=Lectures and Talks">Lectures and Talks</a></li>
                        <li><a href="http://www.mnhs.org/calendar?c=Music and Performances">Music and Performances</a></li>
                        <li><a href="http://www.mnhs.org/calendar?c=Tours">Tours</a></li>
                        <li><a href="http://www.mnhs.org/calendar">All Events</a></li>
                      </ul>
                      <h3 class="menu-feature">Exhibits</h3>
                      <ul class="menu">
                        <li><a href="http://www.minnesotahistorycenter.org/exhibits">History Center Exhibits</a></li>
                      </ul>
                    </div>
                    <div class="grid-6">
                      <h3> <a href="http://www.mnhs.org/visit" class="active-trail active">Our 26 Locations</a> </h3>
                      <hr>
                      <div class="grid-2">
                        <ul>
                          <li><a href="http://sites.mnhs.org/historic-sites/alexander-ramsey-house">Alexander Ramsey House</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/birch-coulee-battlefield">Birch Coulee Battlefield</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/charles-lindbergh-historic-site">Charles A. Lindbergh<br>
                            Historic Site</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/comstock-house">Comstock House</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/folsom-house">Folsom House</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/forest-history-center">Forest History Center</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/fort-ridgely">Fort Ridgely</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/harkin-store">Harkin Store</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/historic-forestville">Historic Forestville</a></li>
                        </ul>
                      </div>
                      <div class="grid-2">
                        <ul>
                          <li><a href="http://www.historicfortsnelling.org">Historic Fort Snelling</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/james-j-hill-house">James J. Hill House</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/jeffers-petroglyphs">Jeffers Petroglyphs</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/lac-qui-parle-mission">Lac qui Parle Mission</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/lower-sioux-agency">Lower Sioux Agency</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/marine-mill">Marine Mill</a></li>
                          <li><a href="http://www.millcitymuseum.org">Mill City Museum</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/mille-lacs-indian-museum">Mille Lacs Indian Museum<br>
                            and Trading Post</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/minnehaha-depot">Minnehaha Depot</a></li>
                        </ul>
                      </div>
                      <div class="grid-2">
                        <ul>
                          <li><a href="http://www.minnesotahistorycenter.org">Minnesota History Center</a>
                            <ul>
                              <li><a href="http://sites.mnhs.org/library">Gale Family Library</a></li>
                            </ul>
                          </li>
                          <li><a href="http://sites.mnhs.org/historic-sites/minnesota-state-capitol">Minnesota State Capitol</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/north-west-company-fur-post">North West Company Fur Post</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/oliver-h-kelley-farm">Oliver Kelley Farm</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/sibley-historic-site">Sibley Historic Site</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/split-rock-lighthouse">Split Rock Lighthouse</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/traverse-des-sioux">Traverse des Sioux</a></li>
                          <li><a href="http://sites.mnhs.org/historic-sites/ww-mayo-house">W.W. Mayo House</a></li>
                        </ul>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="grid-8 top-tier-sites">
                      <hr>
                      <a href="http://www.minnesotahistorycenter.org"><img alt="Minnesota History Center" src="/static/masthead/mnhs_org/img/logos/small/mhc.png" class="logo-mhc"></a> <a href="http://www.historicfortsnelling.org"><img alt="Historic Fort Snelling" src="/static/masthead/mnhs_org/img/logos/small/hfs.png" class="logo-hfs"></a> <a href="http://sites.mnhs.org/historic-sites/split-rock-lighthouse"><img alt="Split Rock Lighthouse" src="/static/masthead/mnhs_org/img/logos/small/srl.png" class="logo-srl"></a> <a href="http://www.millcitymuseum.org"><img alt="Mill City Museum" src="/static/masthead/mnhs_org/img/logos/small/mcm.png" class="logo-mcm"></a> </div>
                  </div>
                </div>
              </div>
              <!-- End Visit Menu Content --> 
            </li>
          </ul>
        </li>
        <!-- End Visit Tab --> 
        <!-- Begin Research Tab -->
        <li class="dropdown research"> <a href="#" data-toggle="dropdown" class="dropdown-toggle">Research<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> 
              <!-- Begin Research Menu Content -->
              <div class="dropmenu-content">
                <div class="container">
                  <div class="row overview-section">
                    <div class="grid-6">
					 <a href="http://www.mnhs.org/research">Overview</a> </div>
                  </div>
                  <div class="row">
                    <div class="grid-3">
                      <h3> <a href="http://www.mnhs.org/research">Records &amp; Indexes</a> </h3>
                      <ul>
                        <li><a href="http://search.mnhs.org/">Search Collections</a></li>
                        <li><a href="http://mnhs.mnpals.net/">Library Catalog</a></li>
                        <li><a href="http://search.mnhs.org/?brand=people">People Finder</a></li>
                        <li><a href="http://search.mnhs.org/?brand=findaids">Archival Collection Finding Aids</a></li>
                        <li><a href="http://search.mnhs.org/?brand=people">Birth Records</a></li>
                        <li><a href="http://search.mnhs.org/?brand=people">Death Records</a></li>
                        <li><a href="http://search.mnhs.org/?brand=people">State Census Records</a></li>
                        <li><a href="http://search.mnhs.org/?brand=people">Veterans' Graves Registry</a></li>
                        <li><a href="http://www.mnhs.org/newspapers">Digital Newspapers</a></li>
                        <li><a href="http://collections.mnhs.org/voicesofmn/">Oral History Collection</a></li>
                        <li><a href="http://collections.mnhs.org/maps/">Maps</a></li>
                        <li><a href="http://www.mnhs.org/nrhp">National Register of Historic Places</a></li>
                        <li><a href="http://www.mnhs.org/mnplaces">Minnesota Place Names</a></li>
                      </ul>
                    </div>
                    <div class="grid-3"><a href="http://sites.mnhs.org/library">
                      <h3> Gale Family Library </h3>
                      <img class="logo-gale" alt="Gale Family Library" src="/static/masthead/mnhs_org/img/gale-family-library-slim.jpg"></a>
                      <h3> <a href="http://www.mnhs.org/research#research-help">Research Help</a> </h3>
                      <ul>
                        <li> <a href="http://libguides.mnhs.org/index.php">Research Guides by Topic</a> </li>
                        <li> <a href="http://sites.mnhs.org/library/video-tutorials">Video Tutorials</a> </li>
                        <li> <a href="http://libguides.mnhs.org/content.php?pid=461515">Family History Guide</a> </li>
                        <li> <a href="http://sites.mnhs.org/library/researchservices">Research Services</a> </li>
                        <li> <a href="http://sites.mnhs.org/library/content/newspaper-collection">Newspaper Resources</a> </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <!-- End Research Menu Content --> 
            </li>
          </ul>
        </li>
        <!-- End Research Tab --> 
        <!-- Begin Preservation Tab -->
        <li class="dropdown preservation"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Preservation<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> <!-- Begin Preservation Menu Content -->
              <div class="dropmenu-content">
                <div class="container">
                  <div class="row">
                    <div class="grid-3">
                      <ul>
                        <li> <a href="http://www.mnhs.org/shpo/grants/">Grants and Financial Incentives</a> </li>
                        <li> <a href="http://www.mnhs.org/shpo/">State Historic Preservation Office</a> </li>
                        <li> <a href="http://www.mnhs.org/shpo/lhs/">Local History Services</a> </li>
                        <li> <a href="http://www.mnhs.org/preserve/records/">Minnesota State Archives</a> </li>
                        <li> <a href="http://www.mnhs.org/preserve/conservation/">Conservation</a> </li>
                        <li> <a href="http://www.mnhs.org/shrab">State Historical Record Advisory Board</a> </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <!-- End Preservation Menu Content --> 
            </li>
          </ul>
        </li>
        <!-- End Preservation Tab --> 
        <!-- Begin Explore Tab -->
        <li class="dropdown explore"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Explore<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> 
              <!-- Begin Explore Content -->
              <div class="dropmenu-content">
                <div class="container">
                  <div class="row overview-section">
                    <div class="grid-6"><a href="http://www.mnhs.org/explore">Overview</a> </div>
                  </div>
                  <div class="row">
                    <div class="grid-3">
                      <h3> <a href="http://www.mnhs.org/explore">Multi-Theme</a> </h3>
                      <ul>
                        <li> <a href="http://www.mnopedia.org/">MNopedia</a> </li>
                        <li> <a href="http://discussions.mnhs.org/collections/">Collections Up Close</a> </li>
                        <li> <a href="http://www.mnhs.org/market/mhspress/minnesotahistory">Minnesota History Magazine</a> </li>
                        <li> <a href="http://www.mnhs.org/mnhspress">MNHS Press Books</a> </li>
                        <li> <a href="http://www.mnopedia.org/thisday">This Day in Minnesota History</a> </li>
                      </ul>
                      <h3> <a href="http://www.mnhs.org/explore#stories">Your Stories</a> </h3>
                      <ul>
                        <li> <a href="http://education.mnhs.org/immigration/">Becoming Minnesotan: Recent Immigrants and Refugees</a> </li>
                        <li> <a href="http://legacy.mnhs.org/transitions/">Transitions: University Avenue</a> </li>
                        <li> <a href="http://legacy.mnhs.org/sharing-community-stories/projects">Sharing Community Stories</a> </li>
                        <li> <a href="http://www.mnhs.org/people/mngg/">Stories of Minnesota's Greatest Generation</a> </li>
                        <li> <a href="http://www.placeography.org/index.php/Main_Page">Placeography</a> </li>
                      </ul>
                    </div>
                    <div class="grid-3">
                      <h3> <a href="http://www.mnhs.org/explore#themes">Single Theme</a> </h3>
                      <ul>
                        <li> <a href="http://www.mnhs.org/hmong">Hmong in Minnesota</a> </li>
                        <li> <a href="http://www.usdakotawar.org/">The U.S.-Dakota War of 1862</a> </li>
                        <li> <a href="http://collections.mnhs.org/jp/">Jeffers Petroglyphs Preservation Project</a> </li>
                        <li> <a href="http://sites.mnhs.org/civil-war/">Minnesota and the Civil War</a> </li>
                        <li> <a href="http://www.mnhs.org/duluthlynchings/">Duluth Lynchings</a> </li>
                        <li> <a href="http://discussions.mnhs.org/10000books/">10,000 Books Blog</a> </li>
                        <li> <a href="http://www.historicfortsnelling.org/a-place-in-time/homepage.php">A Look into Fort Snelling's Past</a> </li>
                        <li> <a href="http://beginningdakota.org/">Dakota Language and Grammar</a> </li>
                        <li> <a href="http://www.inhonorofthepeople.org/">In Honor of the People</a> </li>
                        <li> <a href="http://collections.mnhs.org/sevencouncilfires/">The Seven Council Fires</a> </li>
                        <li> <a href="http://collections.mnhs.org/mnauthors/">Minnesota Author Biographies</a> </li>
                        <li> <a href="http://collections.mnhs.org/battleflags/">The Battle Flags of Minnesota</a> </li>
                        <li> <a href="http://collections.mnhs.org/governors/">Governors of Minnesota</a> </li>
                        <li> <a href="http://www.mnhs.org/talesoftheterritory/">Tales of the Territory</a> </li>
                        <li> <a href="http://www.mnhs.org/forestsfieldsfalls">Forests, Fields and the Falls</a> </li>
                        <li> <a href="http://www.mnhs.org/exhibits/lakestreet/interactive/master.html">21A - Right on Lake Street</a> </li>
                        <li> <a href="http://collections.mnhs.org/mondale/">Walter F. Mondale Collection</a> </li>
                        <li> <a href="http://www.mnhs.org/school/online/communities">Hibbing, Red Wing and St. Anthony</a> </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <!-- End Explore Content --> 
            </li>
          </ul>
        </li>
        <!--End Explore Tab--> 
        <!--Begin Schools Tab-->
        <li class="dropdown schools"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Schools<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> 
              <!-- Begin Schools Menu Content -->
              <div class="dropmenu-content">
                <div class="container">
                  <div class="row">
                    <div class="grid-2">
                      <ul>
                        <li><a href="http://education.mnhs.org/">For Educators</a></li>
                        <li><a href="http://education.mnhs.org/field-trips">Field Trips</a></li>
                        <li><a href="http://education.mnhs.org/northern-lights">Northern Lights Curriculum</a></li>
                        <li><a href="http://education.mnhs.org/historyday">History Day</a></li>
                        <li><a href="http://csse.mnhs.org/">Minnesota Center for Social Studies Education</a></li>
                      </ul>
                    </div>
                    <div class="grid-1"> <a href="http://education.mnhs.org/"><img class="logo-edu" src="/static/masthead/mnhs_org/img/mnStateSmart_100.png" alt="MN State Smart"></a> </div>
                  </div>
                </div>
              </div>
              <!-- End Schools Menu Content --> 
            </li>
          </ul>
        </li>
        <!-- End Schools Tab --> 
        <!--Begin About Tab-->
        <li class="dropdown about"><a href="#" data-toggle="dropdown" class="dropdown-toggle">About MNHS<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> 
              <!-- Begin About Menu Content -->
              <div class="dropmenu-content">
                <div class="container">
                  <div class="row">
                    <div class="grid-3">
                      <ul>
                        <li><a href="http://www.mnhs.org/about">Who We Are</a></li>
                        <li><a href="http://www.mnhs.org/about/mission">Mission, Values &amp; Vision</a></li>
                        <li><a href="http://www.mnhs.org/about/history">History of MNHS</a></li>
                        <li><a href="http://www.mnhs.org/about/leadership">Leadership</a></li>
                        <li><a href="http://www.mnhs.org/contact">Contact Info &amp; Departments</a></li>
                        <li><a href="http://www.mnhs.org/reports">Reports</a></li>
                        <li><a href="http://legacy.mnhs.org/">Legacy Amendment</a></li>
                        <li><a href="http://www.mnhs.org/sustainability">Sustainability</a></li>
                        <li><a href="http://www.mnhs.org/media">Media Room</a></li>
                        <li><a href="http://www.mnhs.org/internships">Internships</a></li>
                        <li><a href="http://www.mnhs.org/fellowships">Fellowships & Residencies</a></li>
                        <li><a href="http://www.mnhs.org/volunteers">Volunteers</a></li>
                        <li><a href="http://www.mnhs.org/jobs">Jobs</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </li>
          </ul>
        </li>
        <!-- End About Tab --> 
        <!--Begin Support Tab-->
        <li class="dropdown support"><a href="#" data-toggle="dropdown" class="dropdown-toggle">Support<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> <!-- Begin Support Menu Content -->
              <div class="dropmenu-content">
                <div class="container">
                  <div class="row">
                    <div class="grid-3">
                      <ul>
                        <li><a href="http://sites.mnhs.org/support">Support MNHS</a></li>
                        <li><a href="http://sites.mnhs.org/support/membership">Become a Member</a></li>
                        <li><a href="http://sites.mnhs.org/support/make-gift">Make a Gift</a></li>
                        <li><a href="http://sites.mnhs.org/support/north-star-circle">North Star Circle</a></li>
                        <li><a href="http://www.mnhs.org/womnhs">Women's Organization of MNHS</a></li>
                        <li><a href="http://www.mnhs-legacy.org/">Your Legacy</a></li>
                        <li><a href="http://www.mnhs.org/historymatters">History Matters — Take Action</a></li>
                        <li><a href="http://sites.mnhs.org/support/corporate-and-foundation-support">Corporate &amp; Foundation Giving</a></li>
                        <li><a href="http://sites.mnhs.org/support/sponsorship">Sponsorship</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <!-- End Support Menu Content --> 
            </li>
          </ul>
        </li>
        <!-- End Support Tab --> 
        <!--Begin Search Tab-->
        <li class="dropdown search"><a href="#" data-toggle="dropdown" class="dropdown-toggle"><img alt="Search" class="search-icon" src="/static/masthead/mnhs_org/img/search.png"><span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li> <!-- Begin Search Menu Content -->
              <div class="dropmenu-content">
                <div class="container">
                  <div class="grid-3">
                        <form method="get" id="menu-search" class="global-search-form" action="http://search.mnhs.org/">
                          <input onkeypress="return checkSubmit(event);" class="input-box" type="text" name="q" maxlength="75" size="75">
                          <input type="hidden" value="websites" name="tab">
                          <input type="image" src="/static/masthead/mnhs_org/img/search.png" name="Search" alt="Search" class="searchKeyword">
                        </form>
                  </div>
                </div>
              </div>
              <!-- End Search Menu Content --> 
            </li>
          </ul>
        </li>
        <!-- End Search Tab -->
      </ul>
    </nav>
  </div>
</div>
</div>
<!-- End Navbar --> 
<link rel='stylesheet' type='text/css' media='all' href="/static/masthead/navbar.css" />
<!--[if lt IE 9]>
<script src="https://cdn.polyfill.io/v1/polyfill.min.js"></script>
<![endif]--> 
<script src="/static/masthead/navbar.js"></script>