
<div id="zone-header-wrapper">
<!-- ****Start Menu**** -->

<div id="masthead">
  <div class="container-12">
    <div class="grid-12">
      <div id="mhs-logo"> <a href="http://www.mnhs.org/"><img alt="Minnesota Historical Society Logo" src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/mhs-logo-white.png" /></a> </div>
      <div id="search-secondaryLinks">
		<div id="global-search">
			<form method="get" class="global-search-form" title="Search the MNHS website and research materials" action="http://search.mnhs.org">
				<input onkeypress="return checkSubmit(event);" class="input-box" title="Enter search query" type="text" name="q" maxlength="75" size="75" />
				<input type="hidden" value="websites" name="tab" />
				<input type="image" src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/search.png" name="Search" alt="Search" class="searchKeyword" />
			</form>
		</div> <!-- end div id=global-search -->
        <div id="secondaryLinks">
          <ul>
            <li><a href="http://sites.mnhs.org/support/make-gift">Donate</a></li>
            <li><a href="http://shop.mnhs.org">Shop</a> | </li>
            <li><a href="http://sites.mnhs.org/support/membership">Membership</a> | </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="clear"> </div>
</div>

<!-- end masthead-->
<div class="mega-container mhs-gray">
  <div class="container-12 megamenu_container_height">
    <div class="grid-12">
      <div id="mhs-flame"> <a href="http://www.mnhs.org/"><img title="Return to MNHS homepage" alt="Minnesota Historical Society M-Flame Logo" src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/mhs-logo-mflame-white.png" /></a> </div>
      <div class="megamenu_container megamenu_dark_bar megamenu_light"> 
        
        <!-- Begin Menu Container -->
        <ul class="megamenu">
          <!-- Begin Mega Menu -->
          <li class="megamenu_button"><a href="#_">Menu</a></li>
          <li class="se-visit section"><a href="http://www.mnhs.org/visit" class="megamenu_drop">Visit</a> 
            <!-- Begin Item -->
            <div class="dropdown_fullwidth"> 
              <!-- Begin Item Container -->
              <div class="col_2">
                <h3 class="menu-feature"> <a href="mnhs.org/calendar" title="">Calendar</a> </h3>
                <ul class="menu">
                  
                  <li><a href="http://www.mnhs.org/calendar?c=American" title="">American Indian Events</a></li>
                  <li><a href="http://www.mnhs.org/calendar?c=Camps" title="">Camps</a></li>
                  <li><a href="http://www.mnhs.org/calendar?c=Classes and Workshops" title="">Classes and Workshops</a></li>
                  <li><a href="http://www.mnhs.org/calendar?c=Family" title="">Family Events</a></li>
                  <li><a href="http://www.mnhs.org/calendar?c=Lectures and Talks" title="">Lectures and Talks</a></li>
                  <li><a href="http://www.mnhs.org/calendar?c=Music and Performances" title="">Music and Performances</a></li>
                  <li><a href="http://www.mnhs.org/calendar?c=Tours" title="">Tours</a></li>
                  <li><a href="mnhs.org/calendar" title="">All Events</a></li></ul>
                  
                     <h3 class="menu-feature"> EXHIBITS </h3>
                     <ul class="menu">
                  <li><a href="http://www.minnesotahistorycenter.org/exhibits" title="">History Center Exhibits</a></li>
                </ul>
              </div>
              <div class="col_10">
                <h3> <a href="http://www.mnhs.org/visit" title="" class="active-trail active">Our 26 Locations</a> </h3>
                <hr />
                <div class="col_4">
                  <ul class="list_unstyled">
                    <li><a href="http://sites.mnhs.org/historic-sites/alexander-ramsey-house">Alexander Ramsey House</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/birch-coulee-battlefield">Birch Coulee Battlefield</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/charles-lindbergh-historic-site">Charles A. Lindbergh<br />
                      Historic Site</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/comstock-house">Comstock House</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/folsom-house">Folsom House</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/forest-history-center">Forest History Center</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/fort-ridgely">Fort Ridgely</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/harkin-store">Harkin Store</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/historic-forestville">Historic Forestville</a></li>
                  </ul>
                </div>
                <div class="col_4">
                  <ul class="list_unstyled">
                    <li><a href="http://www.historicfortsnelling.org">Historic Fort Snelling</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/james-j-hill-house">James J. Hill House</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/jeffers-petroglyphs">Jeffers Petroglyphs</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/lac-qui-parle-mission">Lac qui Parle Mission</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/lower-sioux-agency">Lower Sioux Agency</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/marine-mill">Marine Mill</a></li>
                    <li><a href="http://www.millcitymuseum.org">Mill City Museum</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/mille-lacs-indian-museum">Mille Lacs Indian Museum<br />
                      and Trading Post</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/minnehaha-depot">Minnehaha Depot</a></li>
                  </ul>
                </div>
                <div class="col_4">
                  <ul class="list_unstyled">
                    <li><a href="http://www.minnesotahistorycenter.org">Minnesota History Center</a></li>
                    <li style="list-style-image:none;">&mdash; <a href="http://sites.mnhs.org/library">Gale Family Library</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/minnesota-state-capitol">Minnesota State Capitol</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/north-west-company-fur-post">North West Company Fur Post</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/oliver-h-kelley-farm">Oliver Kelley Farm</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/sibley-historic-site">Sibley Historic Site</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/split-rock-lighthouse">Split Rock Lighthouse</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/traverse-des-sioux">Traverse des Sioux</a></li>
                    <li><a href="http://sites.mnhs.org/historic-sites/ww-mayo-house">W.W. Mayo House</a></li>
                  </ul>
                </div>
              </div>
              <div class="col_12 top-tier-sites">
                <hr>
                <a href="http://www.minnesotahistorycenter.org"><img alt="Minnesota History Center Logo" src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/logos/small/mhc.png" class=" logo-mhc" /></a> <a href="http://www.historicfortsnelling.org"><img alt="Historic Fort Snelling Logo" src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/logos/small/hfs.png" class="logo-hfs" /></a> <a href="http://sites.mnhs.org/historic-sites/split-rock-lighthouse"><img alt="Split Rock Lighthouse Logo" src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/logos/small/srl.png" class="logo-srl" /></a> <a href="http://www.millcitymuseum.org"><img alt="Mill City Museum Logo" src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/logos/small/mcm.png" class=" logo-mcm" /></a> </div>
            </div>
            
            <!-- End Item Container --> 
          </li>
          <!-- End Item -->
          <li class="se-research section"><a href="http://www.mnhs.org/research" class="megamenu_drop">Research</a> 
            <!-- Begin Item -->
            <div class="dropdown_8columns dropdown_container"> 
              <!-- Begin Item Container -->
              <div class="col_6 clearfix">
                <h3> <a href="http://www.mnhs.org/research">Records &amp; Indexes</a> </h3>
					<ul>
						<li><a href="http://search.mnhs.org/">Search Collections</a></li>
						<li><a href="http://mnhs.mnpals.net/">Library Catalog</a></li>
						<li><a href="http://search.mnhs.org/?brand=people">People Finder</a></li>
						<li><a href="http://search.mnhs.org/?brand=findaids">Archival Collection Finding Aids</a></li>
						<li><a href="http://search.mnhs.org/?brand=people">Birth Records</a></li>
						<li><a href="http://search.mnhs.org/?brand=people">Death Records</a></li>
						<li><a href="http://search.mnhs.org/?brand=people">State Census Records</a></li>
						<li><a href="http://search.mnhs.org/?brand=people">Veterans&#39 Graves Registry</a></li>
						<li><a href="http://www.mnhs.org/newspapers">Digital Newspapers</a></li>
						<li><a href="http://collections.mnhs.org/voicesofmn/">Oral History Collection</a></li>
						<li><a href="http://collections.mnhs.org/maps/">Maps</a></li>
						<li><a href="http://nrhp.mnhs.org/">National Register of Historic Places</a></li>
						<li><a href="http://mnplaces.mnhs.org/upham/">Minnesota Place Names</a></li>
					</ul>
              </div>
              <div class="col_6"> <a href="http://sites.mnhs.org/library">
                <h3> Gale Family Library </h3>
                <img style="padding:0 0 25px 0; margin:0;" alt="Gale Family Library" src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/gale-family-library-slim.jpg" /></a>
                <h3> <a href="http://www.mnhs.org/research#research-help">Research Help</a> </h3>
                <ul>
                  <li> <a href="http://libguides.mnhs.org/index.php">Research Guides by Topic</a> </li>
                  <li> <a href="http://sites.mnhs.org/library/video-tutorials">Video Tutorials</a> </li>
                  <li> <a href="http://libguides.mnhs.org/content.php?pid=461515">Family History Guide</a> </li>
                  <li> <a href="http://sites.mnhs.org/library/researchservices">Research Services</a> </li>
                  <li> <a href="http://sites.mnhs.org/library/content/newspaper-collection">Newspaper Resources</a> </li>
                </ul>
              </div>
            </div>
            
            <!-- End Item Container --> 
          </li>
          <!-- End Item -->
          <li class="se-shop section"><a href="http://www.mnhs.org/shpo/" class="megamenu_drop">Preservation</a> 
            <!-- Begin Item -->
            <div class="dropdown_4columns dropdown_container"> 
              <!-- Begin Item Container -->
              <div class="col_12">
                <ul>
                  <li> <a href="http://www.mnhs.org/shpo/grants/">Grants and Financial Incentives</a> </li>
                  <li> <a href="http://www.mnhs.org/shpo/">State Historic Preservation Office</a> </li>
                  <li> <a href="http://www.mnhs.org/shpo/lhs/">Local History Services</a> </li>
                  <li> <a href="http://www.mnhs.org/preserve/records/">Minnesota State Archives</a> </li>
                   <li> <a href="http://www.mnhs.org/preserve/conservation/">Conservation</a> </li>
				  <li> <a href="http://www.mnhs.org/shrab">State Historical Record Advisory Board</a> </li>
                </ul>
              </div>
            </div>
            
            <!-- End Item Container --> 
          </li>
          <!-- End Item -->
          <li class="se-explore section"><a href="http://www.mnhs.org/explore" class="megamenu_drop">Explore</a> 
            <!-- Begin Item -->
            <div class="dropdown_8columns dropdown_container"> 
              <!-- Begin Item Container -->
              <div class="col_6 clearfix">
                <h3> <a href="http://www.mnhs.org/explore">Multi-Theme</a> </h3>
                <ul>
                  <li> <a href="http://www.mnopedia.org">MNopedia</a> </li>
                  <li> <a href="http://discussions.mnhs.org/collections/">Collections Up Close</a> </li>
                  <li> <a href="http://www.mnhs.org/market/mhspress/minnesotahistory/index">Minnesota History Magazine</a> </li>
                  <li> <a href="http://www.mnhs.org/mnhspress">MNHS Press Books</a> </li>
                  <li> <a href="http://www.mngeo.state.mn.us/ghol/">True North: Mapping Minnesota&#039;s History</a> </li>
                  <li> <a href="http://events.mnhs.org/bookofdays/">This Day in Minnesota History</a> </li>
                </ul>
                <h3> <a href="http://www.mnhs.org/explore#stories">Your Stories</a> </h3>
                <ul>
                  <li> <a href="http://education.mnhs.org/immigration/">Becoming Minnesotan: Recent Immigrants and Refugees</a> </li>
                  <li> <a href="http://legacy.mnhs.org/transitions/">Transitions: University Avenue</a> </li>
                  <li> <a href="http://legacy.mnhs.org/sharing-community-stories/projects">Sharing Community Stories</a> </li>
                  <li> <a href="http://www.mnhs.org/people/mngg/index.htm">Stories of Minnesota&#039;s Greatest Generation</a> </li>
                  <li> <a href="http://www.placeography.org/index.php/Main_Page">Placeography</a> </li>
                  

                </ul>
              </div>
              <div class="col_6 clearfix">
                <h3> <a href="http://www.mnhs.org/explore#themes">Single Theme</a> </h3>
                <ul>
				<li> <a href="http://www.mnhs.org/hmong">Hmong in Minnesota</a> </li>
                  <li> <a href="http://www.usdakotawar.org">The U.S.-Dakota War of 1862</a> </li>
				  <li> <a href="http://collections.mnhs.org/jp/">Jeffers Petroglyphs Preservation Project</a> </li>
                  <li> <a href="http://sites.mnhs.org/civil-war/">Minnesota and the Civil War</a> </li>
                  <li> <a href="http://www.mnhs.org/duluthlynchings/">Duluth Lynchings</a> </li>
                  <li> <a href="http://discussions.mnhs.org/10000books/">10,000 Books Blog</a> </li>
                  <li> <a href="http://www.historicfortsnelling.org/a-place-in-time/homepage.php">A Look into Fort Snelling&#039;s Past</a> </li>
<li> <a href="http://beginningdakota.org">Dakota Language and Grammar</a> </li>
                  <li> <a href="http://www.inhonorofthepeople.org">In Honor of the People</a> </li>
                  <li> <a href="http://collections.mnhs.org/sevencouncilfires/">The Seven Council Fires</a> </li>
                  <li> <a href="http://collections.mnhs.org/mnauthors/">Minnesota Author Biographies</a> </li>
                  <li> <a href="http://collections.mnhs.org/battleflags/">The Battle Flags of Minnesota</a> </li>
                  <li> <a href="http://collections.mnhs.org/governors/">Governors of Minnesota</a> </li>
                  <li> <a href="http://www.mnhs.org/forestsfieldsfalls">Forests, Fields and the Falls</a> </li>
                  <li> <a href="http://www.mnhs.org/exhibits/lakestreet/interactive/master.html">21A - Right on Lake Street</a> </li>
                  <li> <a href="http://collections.mnhs.org/mondale/">Walter F. Mondale Collection</a> </li>
                  <li> <a href="http://www.mnhs.org/school/online/communities">Hibbing, Red Wing and St. Anthony</a> </li>
                </ul>
              </div>
            </div>
            
            <!-- End Item container --> 
          </li>
          <!-- End Item -->
          <li class="se-schools section"><a href="http://education.mnhs.org" class="megamenu_drop">Schools</a> 
            <!-- Begin Item -->
            <div class="dropdown_4columns dropdown_container"> 
              <!-- Begin Item Container -->
              <div class="col_8">
                <ul class="menu">
                  <li><a href="http://education.mnhs.org/" title="">For Educators</a></li>
                  <li><a href="http://education.mnhs.org/field-trips" title="">Field Trips</a></li>
                  <li><a href="http://education.mnhs.org/northern-lights" title="">Northern Lights Curriculum</a></li>
                  <li><a href="http://education.mnhs.org/historyday" title="">History Day</a></li>
                  <li><a href="http://csse.mnhs.org" title="">Minnesota Center for Social Studies Education</a></li>
                </ul>
              </div>
              <div class="col_4"> <a href="http://education.mnhs.org"><img src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/mnStateSmart_100.png" alt="MN State Smart logo" /></a> </div>
            </div>
            
            <!-- End Item container --> 
          </li>
          <!-- End Item -->
          <li class="se-about section"><a href="http://www.mnhs.org/about" class="megamenu_drop">About MNHS</a>
            <div class="dropdown_3columns dropdown_container"> 
              
              <!-- Begin Item Container -->
              <div class="col_12">
                <ul class="menu">
                  <li><a href="http://www.mnhs.org/about" title="">Who We Are</a></li>
                  <li><a href="http://www.mnhs.org/about/mission">Mission, Values &amp; Vision</a></li>
                  <li><a href="http://www.mnhs.org/about/history">History of MNHS</a></li>
                  <li><a href="http://www.mnhs.org/about/leadership">Leadership</a></li>
                  <li><a href="http://www.mnhs.org/contact">Contact Info &amp; Departments</a></li>
                  <li><a href="http://www.mnhs.org/reports">Reports</a></li>
				   <li><a href="http://legacy.mnhs.org">Legacy Amendment</a></li>
                  <li><a href="http://events.mnhs.org/media/index.php" title="">Media Room</a></li>
                  <li><a href="http://www.mnhs.org/internships">Internships</a></li>
                  <li><a href="http://www.mnhs.org/fellowships">Fellowships</a></li>
                  <li><a href="http://www.mnhs.org/volunteers">Volunteers</a></li>
                  <li><a href="http://www.mnhs.org/jobs">Jobs</a></li>
                </ul>
              </div>
            </div>
            
            <!-- End Item Container --> 
          </li>
          <!-- End Item -->
          <li class="se-support section"><a href="http://sites.mnhs.org/support" class="megamenu_drop">Support</a> 
            <!-- Begin Item -->
            <div class="dropdown_3columns dropdown_right dropdown_container"> 
              <!-- Begin Item Container -->
              <div class="col_12">
                <ul class="menu">
                  <li><a href="http://sites.mnhs.org/support" title="">Support MNHS</a></li>
                  <li><a href="http://sites.mnhs.org/support/membership" title="">Become a Member</a></li>
                  <li><a href="http://sites.mnhs.org/support/make-gift" title="">Make a Gift</a></li>
                  <li><a href="http://sites.mnhs.org/support/north-star-circle" title="">North Star Circle</a></li>
                  <li><a href="http://www.mnhs.org/womnhs" title="">Women's Organization of MNHS</a></li>
                  <li><a href="http://www.mnhs-legacy.org/" title="">Your Legacy</a></li>
                  <li><a href="http://www.mnhs.org/historymatters">History Matters &mdash; Take Action</a></li>
                  <li><a href="http://sites.mnhs.org/support/corporate-and-foundation-support" title="">Corporate &amp; Foundation Giving</a></li>
                  <li><a href="http://sites.mnhs.org/support/sponsorship" title="">Sponsorship</a></li>
                </ul>
              </div>
            </div>
            
            <!-- End Item Container --> 
          </li>
          <!-- End Item -->
          <li class="se-search hidden section"><a href="javascript:void(0)" class="megamenu_drop"><img alt="Search Dropdown" class="search-icon" src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/search.png" /></a> 
            <!-- Begin Item -->
            <div class="dropdown_4columns dropdown_right dropdown_container"> 
              <!-- Begin Item Container -->
              <div class="col_12">
				<form method="get" id="menu-search" class="global-search-form" title="Search the MNHS website and research materials" action="http://search.mnhs.org">
					<input onkeypress="return checkSubmit(event);" class="input-box" title="Enter search query" type="text" name="q" maxlength="75" size="75" />
					<input type="hidden" value="websites" name="tab" />
					<input type="image" src="http://www.mnhs.org/sites/all/themes/mnhs_org/img/search.png" name="Search" title="Search query submit" alt="Search query submit" class="searchKeyword" />
				</form>
              </div>
            </div>
            
            <!-- End Item Container --> 
          </li>
          <!-- End Item -->
        </ul>
        <!-- End Mega Menu --> 
      </div>
      <!-- End Menu Container --> 
      <script>
(function ($) {
  $(document).ready(function($){
   $('.megamenu').megaMenuCompleteSet({
        menu_speed_show : 50, // Time (in milliseconds) to show a drop down
        menu_speed_hide : 100, // Time (in milliseconds) to hide a drop down
        menu_speed_delay : 100, // Time (in milliseconds) before showing a drop down
        menu_effect : 'hover_fade', // Drop down effect, choose between 'hover_fade', 'hover_slide', etc.
        menu_click_outside : 1, // Clicks outside the drop down close it (1 = true, 0 = false)
        menu_show_onload : 0, // Drop down to show on page load (type the number of the drop down, 0 for none)
        menu_responsive:1 // 1 = Responsive, 0 = Not responsive
    });
    $( '.megamenu li:has(ul)' ).doubleTapToGo();
    $( '.megamenu li:has(form)' ).doubleTapToGo();
})

})(jQuery);
</script> 
    </div>
  </div>
</div>

<!-- ****end Menu**** -->
</div>